# **Python Basics**

In [2]:
# 1.Create a 1D Numpy array and assign values. Then print the values

import numpy as np
array=np.array([1,2,3,4,5])
print(array)

[1 2 3 4 5]


In [3]:
#2. Create a 2D NumPy array and assign values. Then print the values.

import numpy as np
array_2d = np.array ([[1,2,3], [4,5,6], [7,8,9]])
print(array_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
#3. Add a constant value to all elements of a 2D NumPy array.

import numpy as np
array_2d =np.array ([[1,2,3],[4,5,6], [7,8,9]])
constant = 10
array_2d_updated = array_2d + constant
print(array_2d_updated)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [7]:
#4. Subtract a constant value to all elements of a 2D NumPy array.

import numpy as np
array_2d = np. array ([[10,20,30], [40,50,60], [70,80,90]])
constant = 10
array_2d_updated = array_2d - constant
print(array_2d_updated)

[[ 0 10 20]
 [30 40 50]
 [60 70 80]]


In [8]:
# 5. Calculate the sum of all elements of a 2D NumPy array.

import numpy as np
array_2d = np.array ([[1,2,3],[4,5,6],[7,8,9]])
total_sum = np. sum (array_2d)
print(total_sum)

45


In [9]:
#6. Perform element wise sum between two 2D NumPy arrays.

import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[11,12,13],[14,15,16],[17,18,19]])
sum_array= array1+array2
print(sum_array)

[[12 14 16]
 [18 20 22]
 [24 26 28]]


In [10]:
#7. Perform element wise subtraction between two 2D NumPy arrays.

import numpy as np
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
subtraction_array= array1 - array2
print(subtraction_array)

[[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [11]:
#8. Perform matrix multiplication between two 2D NumPy arrays.

import numpy as np
array1=np.array([[1,2,3],[4,5,6],[7,8,9]])
array2=np.array([[11,12,13],[14,15,16],[17,18,19]])
multiplication_array=array1*array2
print(multiplication_array)

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]
